# .streamlit/config.toml
[server]
runOnSave = true
showEmailPrompt = false
maxUploadSize = 20

[theme]
base = "light"
primaryColor = "#2E7D32"                # Deep green accent
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#212121"
linkColor = "#1E88E5"
linkUnderline = false
codeBackgroundColor = "#E8F5E9"
font = "Segoe UI"
baseRadius = "0.5rem"
buttonRadius = "1rem"
borderColor = "#E0E0E0"
dataframeBorderColor = "#BDBDBD"
dataframeHeaderBackgroundColor = "#E0F2F1"
showWidgetBorder = true
showSidebarBorder = false

chartCategoricalColors = [
    "#2E7D32", "#66BB6A", "#FFA726", "#EF5350", "#42A5F5",
    "#AB47BC", "#26A69A", "#FF7043", "#78909C", "#D4E157"
]

chartSequentialColors = [
    "#E8F5E9", "#C8E6C9", "#A5D6A7", "#81C784", "#66BB6A",
    "#4CAF50", "#43A047", "#388E3C", "#2E7D32", "#1B5E20"
]



[theme.sidebar]
primaryColor = "#388E3C"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#E8F5E9"
textColor = "#1B5E20"
linkColor = "#388E3C"
linkUnderline = false
codeBackgroundColor = "#C8E6C9"
font = "sans-serif"
headingFont = "serif"
headingFontSizes = ["1.5rem", "1.25rem", "1.125rem", "1rem", "0.875rem", "0.75rem"]
headingFontWeights = [700, 600, 600, 600, 600, 600]
codeFont = "monospace"
codeFontSize = "0.75rem"
baseRadius = "0.5rem"
buttonRadius = "1rem"
borderColor = "#A5D6A7"
dataframeBorderColor = "#81C784"
dataframeHeaderBackgroundColor = "#C8E6C9"
showWidgetBorder = true
